// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spoke-d/thermionic/internal/clui (interfaces: Command)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	clui "github.com/spoke-d/thermionic/internal/clui"
	flagset "github.com/spoke-d/thermionic/internal/clui/flagset"
	reflect "reflect"
)

// MockCommand is a mock of Command interface
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
}

// MockCommandMockRecorder is the mock recorder for MockCommand
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// FlagSet mocks base method
func (m *MockCommand) FlagSet() *flagset.FlagSet {
	ret := m.ctrl.Call(m, "FlagSet")
	ret0, _ := ret[0].(*flagset.FlagSet)
	return ret0
}

// FlagSet indicates an expected call of FlagSet
func (mr *MockCommandMockRecorder) FlagSet() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlagSet", reflect.TypeOf((*MockCommand)(nil).FlagSet))
}

// Help mocks base method
func (m *MockCommand) Help() string {
	ret := m.ctrl.Call(m, "Help")
	ret0, _ := ret[0].(string)
	return ret0
}

// Help indicates an expected call of Help
func (mr *MockCommandMockRecorder) Help() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Help", reflect.TypeOf((*MockCommand)(nil).Help))
}

// Run mocks base method
func (m *MockCommand) Run() clui.ExitCode {
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(clui.ExitCode)
	return ret0
}

// Run indicates an expected call of Run
func (mr *MockCommandMockRecorder) Run() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCommand)(nil).Run))
}

// Synopsis mocks base method
func (m *MockCommand) Synopsis() string {
	ret := m.ctrl.Call(m, "Synopsis")
	ret0, _ := ret[0].(string)
	return ret0
}

// Synopsis indicates an expected call of Synopsis
func (mr *MockCommandMockRecorder) Synopsis() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Synopsis", reflect.TypeOf((*MockCommand)(nil).Synopsis))
}

// UI mocks base method
func (m *MockCommand) UI() clui.UI {
	ret := m.ctrl.Call(m, "UI")
	ret0, _ := ret[0].(clui.UI)
	return ret0
}

// UI indicates an expected call of UI
func (mr *MockCommandMockRecorder) UI() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UI", reflect.TypeOf((*MockCommand)(nil).UI))
}
