// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spoke-d/thermionic/internal/cluster/membership (interfaces: OS)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	user "os/user"
	reflect "reflect"
)

// MockOS is a mock of OS interface
type MockOS struct {
	ctrl     *gomock.Controller
	recorder *MockOSMockRecorder
}

// MockOSMockRecorder is the mock recorder for MockOS
type MockOSMockRecorder struct {
	mock *MockOS
}

// NewMockOS creates a new mock instance
func NewMockOS(ctrl *gomock.Controller) *MockOS {
	mock := &MockOS{ctrl: ctrl}
	mock.recorder = &MockOSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockOS) EXPECT() *MockOSMockRecorder {
	return m.recorder
}

// GlobalDatabaseDir mocks base method
func (m *MockOS) GlobalDatabaseDir() string {
	ret := m.ctrl.Call(m, "GlobalDatabaseDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// GlobalDatabaseDir indicates an expected call of GlobalDatabaseDir
func (mr *MockOSMockRecorder) GlobalDatabaseDir() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalDatabaseDir", reflect.TypeOf((*MockOS)(nil).GlobalDatabaseDir))
}

// GlobalDatabasePath mocks base method
func (m *MockOS) GlobalDatabasePath() string {
	ret := m.ctrl.Call(m, "GlobalDatabasePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GlobalDatabasePath indicates an expected call of GlobalDatabasePath
func (mr *MockOSMockRecorder) GlobalDatabasePath() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalDatabasePath", reflect.TypeOf((*MockOS)(nil).GlobalDatabasePath))
}

// HostNames mocks base method
func (m *MockOS) HostNames() ([]string, error) {
	ret := m.ctrl.Call(m, "HostNames")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HostNames indicates an expected call of HostNames
func (mr *MockOSMockRecorder) HostNames() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HostNames", reflect.TypeOf((*MockOS)(nil).HostNames))
}

// Hostname mocks base method
func (m *MockOS) Hostname() (string, error) {
	ret := m.ctrl.Call(m, "Hostname")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hostname indicates an expected call of Hostname
func (mr *MockOSMockRecorder) Hostname() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hostname", reflect.TypeOf((*MockOS)(nil).Hostname))
}

// LocalDatabasePath mocks base method
func (m *MockOS) LocalDatabasePath() string {
	ret := m.ctrl.Call(m, "LocalDatabasePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// LocalDatabasePath indicates an expected call of LocalDatabasePath
func (mr *MockOSMockRecorder) LocalDatabasePath() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocalDatabasePath", reflect.TypeOf((*MockOS)(nil).LocalDatabasePath))
}

// User mocks base method
func (m *MockOS) User() (*user.User, error) {
	ret := m.ctrl.Call(m, "User")
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User
func (mr *MockOSMockRecorder) User() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockOS)(nil).User))
}

// VarDir mocks base method
func (m *MockOS) VarDir() string {
	ret := m.ctrl.Call(m, "VarDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// VarDir indicates an expected call of VarDir
func (mr *MockOSMockRecorder) VarDir() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VarDir", reflect.TypeOf((*MockOS)(nil).VarDir))
}
