// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spoke-d/thermionic/internal/cluster/events (interfaces: Client)

// Package mocks is a generated GoMock package.
package mocks

import (
	client "github.com/spoke-d/thermionic/pkg/client"
	gomock "github.com/golang/mock/gomock"
	websocket "github.com/gorilla/websocket"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Query mocks base method
func (m *MockClient) Query(arg0, arg1 string, arg2 interface{}, arg3 string) (*client.Response, string, error) {
	ret := m.ctrl.Call(m, "Query", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*client.Response)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Query indicates an expected call of Query
func (mr *MockClientMockRecorder) Query(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockClient)(nil).Query), arg0, arg1, arg2, arg3)
}

// Websocket mocks base method
func (m *MockClient) Websocket(arg0 string) (*websocket.Conn, error) {
	ret := m.ctrl.Call(m, "Websocket", arg0)
	ret0, _ := ret[0].(*websocket.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Websocket indicates an expected call of Websocket
func (mr *MockClientMockRecorder) Websocket(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Websocket", reflect.TypeOf((*MockClient)(nil).Websocket), arg0)
}
