// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spoke-d/thermionic/internal/cluster/heartbeat (interfaces: Task)

// Package mocks is a generated GoMock package.
package mocks

import (
	task "github.com/spoke-d/thermionic/internal/task"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockTask is a mock of Task interface
type MockTask struct {
	ctrl     *gomock.Controller
	recorder *MockTaskMockRecorder
}

// MockTaskMockRecorder is the mock recorder for MockTask
type MockTaskMockRecorder struct {
	mock *MockTask
}

// NewMockTask creates a new mock instance
func NewMockTask(ctrl *gomock.Controller) *MockTask {
	mock := &MockTask{ctrl: ctrl}
	mock.recorder = &MockTaskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTask) EXPECT() *MockTaskMockRecorder {
	return m.recorder
}

// Every mocks base method
func (m *MockTask) Every(arg0 time.Duration, arg1 ...task.EveryOption) task.Schedule {
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Every", varargs...)
	ret0, _ := ret[0].(task.Schedule)
	return ret0
}

// Every indicates an expected call of Every
func (mr *MockTaskMockRecorder) Every(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Every", reflect.TypeOf((*MockTask)(nil).Every), varargs...)
}
