// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spoke-d/thermionic/internal/cluster/raft (interfaces: Node,RaftNodeMediator)

// Package mocks is a generated GoMock package.
package mocks

import (
	config "github.com/spoke-d/thermionic/internal/config"
	db "github.com/spoke-d/thermionic/internal/db"
	node "github.com/spoke-d/thermionic/internal/node"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockNode is a mock of Node interface
type MockNode struct {
	ctrl     *gomock.Controller
	recorder *MockNodeMockRecorder
}

// MockNodeMockRecorder is the mock recorder for MockNode
type MockNodeMockRecorder struct {
	mock *MockNode
}

// NewMockNode creates a new mock instance
func NewMockNode(ctrl *gomock.Controller) *MockNode {
	mock := &MockNode{ctrl: ctrl}
	mock.recorder = &MockNodeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNode) EXPECT() *MockNodeMockRecorder {
	return m.recorder
}

// Dir mocks base method
func (m *MockNode) Dir() string {
	ret := m.ctrl.Call(m, "Dir")
	ret0, _ := ret[0].(string)
	return ret0
}

// Dir indicates an expected call of Dir
func (mr *MockNodeMockRecorder) Dir() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dir", reflect.TypeOf((*MockNode)(nil).Dir))
}

// Transaction mocks base method
func (m *MockNode) Transaction(arg0 func(*db.NodeTx) error) error {
	ret := m.ctrl.Call(m, "Transaction", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction
func (mr *MockNodeMockRecorder) Transaction(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockNode)(nil).Transaction), arg0)
}

// MockRaftNodeMediator is a mock of RaftNodeMediator interface
type MockRaftNodeMediator struct {
	ctrl     *gomock.Controller
	recorder *MockRaftNodeMediatorMockRecorder
}

// MockRaftNodeMediatorMockRecorder is the mock recorder for MockRaftNodeMediator
type MockRaftNodeMediatorMockRecorder struct {
	mock *MockRaftNodeMediator
}

// NewMockRaftNodeMediator creates a new mock instance
func NewMockRaftNodeMediator(ctrl *gomock.Controller) *MockRaftNodeMediator {
	mock := &MockRaftNodeMediator{ctrl: ctrl}
	mock.recorder = &MockRaftNodeMediatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRaftNodeMediator) EXPECT() *MockRaftNodeMediatorMockRecorder {
	return m.recorder
}

// DetermineRaftNode mocks base method
func (m *MockRaftNodeMediator) DetermineRaftNode(arg0 node.Tx, arg1 config.Schema) (*db.RaftNode, error) {
	ret := m.ctrl.Call(m, "DetermineRaftNode", arg0, arg1)
	ret0, _ := ret[0].(*db.RaftNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetermineRaftNode indicates an expected call of DetermineRaftNode
func (mr *MockRaftNodeMediatorMockRecorder) DetermineRaftNode(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetermineRaftNode", reflect.TypeOf((*MockRaftNodeMediator)(nil).DetermineRaftNode), arg0, arg1)
}
